//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PhoneStoreWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_Product
    {
        public int id { get; set; }
        public string Title { get; set; }
        public string Description { get; set; }
        public string Detail { get; set; }
        public string Image { get; set; }
        public Nullable<decimal> Price { get; set; }
        public Nullable<decimal> PriceSale { get; set; }
        public Nullable<int> Quantity { get; set; }
        public string SeoTitle { get; set; }
        public string SeoDesscription { get; set; }
        public string SeoKeywords { get; set; }
        public string Meta { get; set; }
        public Nullable<bool> Hide { get; set; }
        public Nullable<int> Position { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public string CreateBy { get; set; }
        public Nullable<System.DateTime> ModifierDate { get; set; }
        public string ModifierBy { get; set; }
        public string ProductCategory { get; set; }
    }
}
